### ISSUE TITLE
Profit doesn't change when changing currency. Wagered amount is completly different

### ISSUE THREAD

**Issue by Bullnados** [Seuntjie900/DiceBot#10]
Last issue if thats no issue again. I promise :smile:
Profit doesn't change when u change currency BTC-->LTC
And the wagered amount isnt confirm with the website amount.

**Comment by Seuntjie900** [comment]
On which site is this?
and which profit? the one showing the account stats (in the main form) or the one showing the session stats (the stats window)

**Comment by Bullnados** [comment]
999dice.
Main form, stats windows is ok

**Comment by Seuntjie900** [comment]
This should be fixed in the latest version. Can you confirm?

**Comment by Bullnados** [comment]
No at the Moment it seems that the profit is fix. and wagered amount is always zero.
