### ISSUE TITLE
Request: Stop condition after xx bets and xx min

### ISSUE THREAD

**Issue by Bullnados** [Seuntjie900/DiceBot#11]
Nice additional stop conditoin in advanced mode would be stoping after xx bets(win+lose) and stoping after xx minutes.

**Comment by Seuntjie900** [comment]
Could you test out the stop and reset conditions added to this version and let me know if they work or not, and if not, what seems to be wrong with them: http://bot.seuntjie.com/botpage.aspx?id=18

I am aware that they are not being written to the save file
