### ISSUE TITLE
Add Support for MoneroDice (now that we have an API:)

### ISSUE THREAD

**Issue by fluffypony** [Seuntjie900/DiceBot#12]
Howzit! To save you the hassle of having to muck around with scraping and parsing the DOM, we added an API to MoneroDice. You can check it out here: http://monerodice.net/api (you'll have to register if you aren't already).

Let me know if there are any methods that are missing, but we'd really love to see MoneroDice support added to DiceBot.

PS. If you're going to be anywhere near Plett in the holidays we must go grab a beer, I'd love to get your input on MoneroDice and what we can do to improve.

**Comment by Seuntjie900** [comment]
Sorry for the slow response. I sent you guys an email on support@monerodice.net

**Comment by fluffypony** [comment]
Received - thanks!
