### ISSUE TITLE
Suggestion/Request: Option to preserve decimal places

### ISSUE THREAD

**Issue by Nixtren** [Seuntjie900/DiceBot#13]
![Screenshot](http://i.imgur.com/xvVagdP.png)

It would be nice to have an option to preserve decimal places in that table. Example:
```
0.0000001   <-- Decimal places not preserved
0.00000010  <-- Decimal places preserved
```

Thanks :-)

**Comment by Seuntjie900** [comment]
Will be fixed in the next beta/version
