### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by asoulay** [Seuntjie900/DiceBot#15]
When I installed DiceBot-3.1.5 FileNotFoundException Occurs.
![err](https://cloud.githubusercontent.com/assets/18721972/14889476/f93043c8-0d84-11e6-9907-02f232c64b2b.jpg)

**Comment by Seuntjie900** [comment]
Kindly see the FAQ on my website, specifically the "When I run Dicebot, it gives me one of the following errors: Not a valid win32 application System.IO.FileNotFoundException DiceBot has stopped working or similar problems" question: https://bot.seuntjie.com/FAQs.aspx?topic=1#faq21
