### ISSUE TITLE
Visua Studio NuGet Requirements

### ISSUE THREAD

**Issue by plexorama** [Seuntjie900/DiceBot#18]
Hi, 

I'm trying to compile DiceBot with VS2015 but I'm running into a load of errors, mainly because of missing dependencies. Please, can you provide a full list of the NuGet packages and/or other dependencies, that are required to successfully compile DiceBot. I would like to add some useful extensions/configuration parameters to the bot. 

Thank you!
Plexo

**Comment by Deadlyhacker** [comment]
Just download non open source and copy paste the .DLL files from it to your project or add them to referances.

**Comment by Seuntjie900** [comment]
I should probably include build instructions on the readme page, but here goes:

Github repos you need: 
Websocket4net: https://github.com/kerryjiang/WebSocket4Net/ (this might require supersocket as to compile)
JDCAPI: https://github.com/Seuntjie900/jdcapi (requires the websocket4net lib compile above)

Nuget: SharpLUA
Noesis.Javascript
SignalrClient
json.net
sqlite core

The nuget packages should resolve if you right click on the project in VS, select manage Nuget and then restore the packages. This will kind of work for Neosis, but only kind of. the JS lib is very weird, I'd recommend just removing the reference and manually adding the reference again to the 64bit Noesis library.

**Comment by plexorama** [comment]
Thanks! I'll try that. Btw, the Noesis package acts really weird. While playing with it, I noticed you have to add it after all other packages have been added. Its integrates better when you download the Noesis source package and add the project to the solution. 
 
btw, which VS version do you use? Maybe it helps to have the same version installed.

**Comment by plexorama** [comment]
btw., if I fail compiling the project, would you mind adding an option to set a fixed seed for FortuneJack and maybe other sites too? The current FJ implementation always uses a random seed value, which is not always what people want.

**Comment by Seuntjie900** [comment]
Yes the Noesis package is a bitch and causes a lot of problems. Maybe if you posted you error I could help you fix it? I've compiled it on both 2013 community, 2015 community and 2015 pro.

This is one of those cases where idgaf what people want. Using the same seed over and over again exposes the gambler to cheating on the server side. If the majority of you bets are in the same direction and uses the same seed, the server can test server seeds and give seeds that can make you lose based on the direction and seed bias you have created. There's no way of proving the site cheated with this method. (this is why i dislike per-bet based server seeds.) Using a random client seed for each bet protects the bettor from this.
