### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by plexorama** [Seuntjie900/DiceBot#19]
I've got a strange UI bug. The bot was already running for more than 24hours. Suddenly, the UI elements disappeared and the status bar was resized over the whole client area. see pic. 

![image](https://cloud.githubusercontent.com/assets/605167/15254589/cac09808-1937-11e6-801a-3fe23f78eb58.png)

**Comment by Seuntjie900** [comment]
I'm aware of this issue, see https://bitcointalk.org/index.php?topic=307425.msg14674738#msg14674738
