### ISSUE TITLE
"nextbet" Bug

### ISSUE THREAD

**Issue by DiceBotReporter** [Seuntjie900/DiceBot#22]
In a short term:You cant change the Amount of program bets in anyway from programmer mode.

Dicebot Version -> Downloaded From Github.com Than Builded With VS.

When you try to use "nextbet" its not working because its only using Starting Bet as a bet amount.

Starting bet =  Settings mode -> Advanced - Stratigies -> Settings -> Starting bet

Update:This Problem Created With Commit Number 84c42acce6c191f31e879b5acf3e4f2a30050b42

**Comment by Seuntjie900** [comment]
Seems lua doesn't support decimals. I remember running into a similar situation earlier on. Thanks for letting me know.
