### ISSUE TITLE
Cannot implicitly convert type 'double' to 'decimal'. An explicit conversion exists

### ISSUE THREAD

**Issue by DiceBotReporter** [Seuntjie900/DiceBot#24]
in "moneypot.cs"

`        public override decimal GetLucky(string server, string client, int nonce)
         {
            long cl = long.Parse(client);
            double roll = Math.Floor((100.0 / 4294967296.0) * (double)((long)(((double)nonce) + cl) % (long)                                                          (4294967296)) * (long)100) / (long)100;
            return roll;
        }
    }`

This lines gives you this error when trying to build.
This happened with [Commit](https://github.com/Seuntjie900/DiceBot/commit/7615c4925f6819119ccf1c9679bd641944cc770a)

**Comment by Seuntjie900** [comment]
Sync to the new commit

**Comment by DiceBotReporter** [comment]
Okay Thank you and sorry for opening Issue maybe too early.
