### ISSUE TITLE
Request: Stop condition: Lower limit

### ISSUE THREAD

**Issue by Bullnados** [Seuntjie900/DiceBot#3]
First. Realy nice piece of software :+1: 
Is it possible to create an option that allows you to increase your lower limit automaticly?
For example:
Balance 100
Lower limit 90
if you win und your balance increace to 110 set lower limit automaticly to 100. Of course with a chooseable own value

**Comment by Seuntjie900** [comment]
This would be extremely hard to implement in a way that would satisfy most users. I suggest taking a look at the programmer mode for customization such as these. You can still use the strategy you set up in the advanced mode from the programmer mode. Below is an example script of how the low limit would be implemented along with the advanced mode strategies:

nextbet=0.00000001 --or whatever your starting bet is.
enablezz=true --this will enable switching high/low according to your advanced zigzag settings
enablesrc=true --this will enable the stop and reset conditions as set up in your advanced settings
startbal=balance
lowlimit=startbal-10 --customize this to the values you need
function dobet()
  if startbal==0 then
    startbal= balance
    lowlimit=startbal-10 --customize this to the values you need
  end
  nextbet = martingale(win) --replace martingale with fibonacci, labouchere or whatever you use
  if balance<=lowlimit then 
    stop() 
  end
  if balance-startbal>= 10 then -- be sure to update this line as 
    --well if you change the at the beginning of the script
    startbal= balance
    lowlimit= startbal
  end
end


see http://bot.seuntjie.com/programmermode.aspx for help on using the programmer mode

**Comment by Bullnados** [comment]
Thanks. Hope geht time to test that
