### ISSUE TITLE
bitsler, login error, captcha

### ISSUE THREAD

**Issue by Hans-Maulwurf** [Seuntjie900/DiceBot#30]
since a few days it's not possibble to login to bitler with the bot because it throws a captcha error?

**Comment by evertongalves** [comment]
I can not log in to bitsler with dicebot, this is okay ... username, password .... what can I do ??

**Comment by sriravi88** [comment]
Friends i also have the same problem .. what is the solution?

**Comment by Seuntjie900** [comment]
Use your username, password AND API key. If you have 2fa enabled, you need to enter your 2fa code as well. 

Username, password and API key are all REQUIRED, you HAVE to enter them all.
