### ISSUE TITLE
Withdraw 999doge (decimal)

### ISSUE THREAD

**Issue by nammmmm** [Seuntjie900/DiceBot#31]
Hello,
thanks for your bot, its a nice one!

I have a problem with the Withdraw function on 999Dice.
When withdrawing to USERID,
 - if i withdraw round amounts like 100 (no decimal), it works like a charm using withdraw(100, "USERID")
 - if i withdraw decimal amounts like 100.1, it's not working at all using withdraw(100.1, "USERID")

i tried to change DOT by COMA but it gives error of course since the coma is used to separate the arguments parameters of the function itself.

Please, do you have any workaround? cause i can only play on Doge because of this yet since my other currencies are <0
thank you

**Comment by Seuntjie900** [comment]
Hi

I wasn't able to reproduce the problem, but I implemented something that should fix it in the next version.

**Comment by nammmmm** [comment]
Thank you for your answer :)
Just a question tho now, do i have to use dots or comas now to withdraw decimal amounts? (comas wont work of course, but maybe i should use a variable like withdrawamount = 1,01 and then withdraw(withdrawamount, "address")

**Comment by Seuntjie900** [comment]
Does it sill not work on the new version? I tested and it worked fine for me.
