### ISSUE TITLE
provalyio.cs in Source Code missing.

### ISSUE THREAD

**Issue by Avanatiker** [Seuntjie900/DiceBot#32]
Iam not able to compile the project because of this missing file.
Visual Studio 2015 says:

> The item 'provablyio.cs' does not exist in the project directory. It may have been moved, renamed or deleted.

In the main source on github its missing too.

**Comment by Seuntjie900** [comment]
Ah, I forgot to exclude the file from the project. You can exclude the file
by removing
<Compile Include="provablyio.cs" />

From the dicebot.Csproj file or just create an empty file with the same
name in the project.

I'll push a fix in a few hours anyway.
