### ISSUE TITLE
Nil Using getHistoryByQuery

### ISSUE THREAD

**Issue by KryptoNova** [Seuntjie900/DiceBot#37]
I absolutely love your work!

In the programmer mode, I am trying to track high/low patterns.  I saw your recommendation to use getHistoryByQuery method to obtain that.  However, every time I try I get a "[string "chunk"]:27: attempt to index local 'myData' (a nil value)" error.

To get the last game's roll value, I was using this query that works in the Firefox SQLite Manager:
`SELECT * FROM bet m WHERE m.betid IN (SELECT max(s.betid) FROM bet s)
`

Since that was not returning a result, I scaled it back to:
`SELECT * FROM bet`

The query above should return similar results as the getHistory() method, but it returns the nil value error.  The odd thing is that when I use getHistory(), I get the data, but it is not in order and I am concerned about the amount of IO that gets consumed when pulling all rows.

This is the function that I am using

```lua
function getLastLucky ()
  local pSQL = "SELECT * FROM bet m WHERE m.betid IN (SELECT max(s.betid) FROM bet s);"
  local myData = getHistoryByQuery(pSQL)
  print("My Data:  "..myData[1].Roll)
  return myData[1].Roll
end

```
This seems that it should work.  Could you take a look and see if this makes sense to you?
I'm thinking this may be a bug, but I'm not sure.  I don't know lua good enough to be able to know for sure.  I've been trying for about three hours now to get this to work.  :-(

Thanks!

**Comment by Seuntjie900** [comment]
There is a bug in some of the sql helper functions, I will get them fixed.

Though I do need to mention that you don't need to query the db to get the bet info for your latest bet. You can use the lastBet object. It's the same object type that gets returned in the gethistory functions.

You should only use the getHistory functions if you need to get a list of bets, or bets from longer ago.

**Comment by KryptoNova** [comment]
Seuntjie900,

Thank you very much!
The rational behind the SQL query is related to finding the last Roll/Lucky value that was posted to the DB.  It doesn't seem to be one of the live variables, so it needs to be pulled from the DB.

I would like to run some statistics on the values of the Roll values.  Maybe something there for some sites, but most likely not.

Thanks again and I'm looking forward to the next version.  :-)

**Comment by Seuntjie900** [comment]
Use lastBet.Roll for you last roll/lucky number.

**Comment by KryptoNova** [comment]
Seuntjie900,

That was exactly what I was looking for!!  I didn't realize what members the "Bet" object would expose in lua.  I guess I don't necessarily need the SQL at this point, but maybe down the road.  I appreciate you looking into addressing that.

Again, thank you so much for this project.  I really appreciate your work and dedication.
