### ISSUE TITLE
Stop condition: When limit is reached; Reset after programm start

### ISSUE THREAD

**Issue by Bullnados** [Seuntjie900/DiceBot#4]
Is that normal that the selection on "When limit is reached" is reseted after programm is restarted?

**Comment by Seuntjie900** [comment]
No, It's a known bug in 3.0.1, but should be fixed in 3.0.2 and is definitely fixed in 3.0.3 beta. Changing between sites can reset it because not all sites allow investing and/or withdrawing through the api.

**Comment by Bullnados** [comment]
Ok I'm using 3.0.2 Nothing chrashed, no site switching. 
Ok than i wait fpr 3.0.3
