### ISSUE TITLE
martingale bets not incrementing

### ISSUE THREAD

**Issue by coreylschneider** [Seuntjie900/DiceBot#52]
When using your application the 'martingale' selection is NOT incrementing the bet amount.

**Comment by Seuntjie900** [comment]
Working fine for me. can you provide a screenshot of your settings and the incorrect behaviour? Or steps to reproduce the problem?

**Comment by coreylschneider** [comment]
greetings Suentjie, 

this issue was in 3.3.12, i have updated to 3.3.13 and all seems well :)  I think my issue was linked to an old settings file possibly.. but i deleted the C:\user\usrname\appdata\roaming\dicebot....\settings.files then downloaded the latest version. 

Closing issue. 

Cheers!
