### ISSUE TITLE
Sometimes DiceBot stop without a reason

### ISSUE THREAD

**Issue by Bullnados** [Seuntjie900/DiceBot#6]
Today I get a message, somethin wrong. But I dont know why? No Limits, enough balance.
This is the secondor third time i got that. 
Imo it is importend that #5 is implemented.

**Comment by Seuntjie900** [comment]
if it says something went wrong, it's usually a network error and the bot stops to protect the user. Lets say for example you're doing martingale:
1l
2l
4l
8l
16l
32l
64l
128w, but a network error occurs. Your bet gets processed by the server but you don't receive the result of the bet.
The bot retries 128 and loses
256l
512l and you bust.

**Comment by Bullnados** [comment]
Ok thanks. Than it's a feature not a bug^^.
But than an option would be nice, u can decide what message lvl u want to see :smiley:

**Comment by Seuntjie900** [comment]
I've been meaning on implementing a logging function in the bot with different logging levels, but haven't gotten around to it yet.
