### ISSUE TITLE
Load programmer mode script on start

### ISSUE THREAD

**Issue by Subcode** [Seuntjie900/DiceBot#61]
Hi,

I was wondering if its possible to automatically load some settings on start?
Currently when i start the app, it always starts on PrimeDice->btc, which i don't use.
Then i have to fill in the API key, which auto login does not seem to have a setting for.
And after this i also have to fill in the script that i want to use.
I would love it if it was possible to change the site that loads on start as wel as the default script it loads. Having an option for the API key at auto login would also be great (unless it automatically uses the password field for the API key, but i cannot find any info about this.)

Thanks a lot, and please let me know.

edit: part of this would be easily achieved by loading TempCodeBackup.txt on startup.

**Comment by Seuntjie900** [comment]
Settings are already being loaded on start. The bot should automatically load the last site that you used, but it does not select your currency.

Password in autologin can be used for API key.

The changes you're requesting are outside of the scope of maintenance I am doing on v3 (bug fixes, new sites). I barely have the time to work on the bot anymore, and any time I do have, I want to work on v4. If someone else makes these changes and does a pull request, I'll merge review and merge them if the code quality is good enough.
