### ISSUE TITLE
wrong result matematic a+=0.01

### ISSUE THREAD

**Issue by Serviso** [Seuntjie900/DiceBot#70]
c = 0 for q=1 , 300 do c+=0.01 print(c) end the result wrong in number q=80 and up please do checked the result in console

**Comment by Seuntjie900** [comment]
This isn't an error in DiceBot, this is a result of doing decimal arithmetic with a floating point decimal type. You will get the same or similar results in every language when you use a float with the same code, for some it might just take longer depending how the precision of the float in that language. Hell, you can even make it happen in excel without too much difficulty.

You need to manage your arithmetic yourself:
https://en.wikipedia.org/wiki/Floating-point_error_mitigation
https://stackoverflow.com/questions/47634766/algorithm-to-correct-the-floating-point-precision-error-in-javascript

IMO easiest option for managing floats is deciding how many significant decimals your numbers have and rounding to that after every calculation or working with ints and converting from decimal->int or int-> decimal when you need to use value.
